Support for Code Snippets in Editor
semadox/streamlit_monaco_yaml pull request #2
Opened 2023-09-11 09:46 UTC by julian-r

2023-09-12 12:08 UTC, trojanowski requested changes
@julian-r currently we should also run `./build.sh` and add the changes to the commit. Alternatively we could setup CI to do it automatically there.

2023-09-12 12:08 UTC, trojanowski commented on frontend/src/Monaco.tsx
> +    console.log(currentArgs.current.snippets);
To remove

2023-09-12 12:08 UTC, trojanowski commented on frontend/src/Monaco.tsx
> +        console.log("called completion")
To remove

2023-09-12 12:09 UTC, trojanowski commented on frontend/src/Monaco.tsx
> +          // documentation: snippet.detail,
To delete?

2023-09-15 08:58 UTC, julian-r commented on streamlit_monaco_yaml/__init__.py
> +    snippets: list[Snippet] = None,
A list is expected :)

2023-09-15 12:00 UTC, trojanowski approved these changes

2023-09-15 12:01 UTC, merged